### ISSUE TITLE
Think about exporting the signature matrices from MuSiC und SCDC

### ISSUE THREAD

**Issue by PelzKo** [omnideconv/omnideconv#64]
It is not possible to use music and scdc with a foreign signature matrix, but it should be possible to export theirs for the use in other methods

**Comment by LorenzoMerotto** [comment]
(I'm going through all the issues rn since I'm working on the package)

It does not make much sense to export MuSiC and SCDC signatures IMO because they require the use of the variances of the clustering results on cell types and variances of genes as well
This means that the signatures could only be used by those methods in a meaningful way

**Comment by grst** [comment]
this would anyway only relevant for the benchmark. Let's close it then!
