### ISSUE TITLE
cell-type remapping

### ISSUE THREAD

**Issue by grst** [omnideconv/omnideconv#92]
Here is how this is done in immunedeconv (it recursively traverses a cell-type tree) 
https://github.com/icbi-lab/immunedeconv/blob/c70539f2b08901687561dca755337fc6a5130440/R/cell_type_mapping.R#L80-L100

Here is the definition of the cell-type tree and the mapping in different sheets: 
https://github.com/icbi-lab/immunedeconv/blob/master/inst/extdata/cell_type_mapping.xlsx

But as we discussed in the call it might be beneficial to remap the cell-types *before* creating the signature matrix, 
and to use cell-type labels from the cell ontology (which also provides a tree!)

**Comment by LorenzoMerotto** [comment]
It's not that easy to do it for the benchmarking since it all depends on the type of labels that we have in the single cell/bulk datasets, and wiht the simulator we directly choose which cell types we want. 
It could be a fnuctionality to add in the future but we need the users to provide cell-ontology labels
